/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal.java.project.PanelPackege;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import pkgfinal.java.project.*;
import javax.swing.table.*;
import pkgfinal.java.project.*;
import static pkgfinal.java.project.FinalJavaProject.*;
import  pkgfinal.java.project.FinalJavaProject.*;
import static pkgfinal.java.project.FinalJavaProject.fillArrayFtomDataBase;
import static pkgfinal.java.project.FinalJavaProject.query;
import static pkgfinal.java.project.FinalJavaProject.r;
import static pkgfinal.java.project.FinalJavaProject.ss;
/**
 *
 * @author c.city
 */
public class define extends javax.swing.JPanel {

    int indexOfCustomer;

    /**
     * Creates new form define
     */
    public define() {
        initComponents();
    }

    public define(int indexOfCustomer) {
        this.indexOfCustomer = indexOfCustomer;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDefine1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldTraiff = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldMeterCode = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDefine = new javax.swing.JTable();
        jButtonSearch = new javax.swing.JButton();

        jTableDefine1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Metercode", "Region", "Traiff", "Bill"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableDefine1);

        jLabel1.setText("Traiff");

        jTextFieldTraiff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTraiffActionPerformed(evt);
            }
        });

        jLabel2.setText("MeterCode");

        jTextFieldMeterCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMeterCodeActionPerformed(evt);
            }
        });

        jButton1.setText("Define");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTableDefine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Metercode", "Region", "Traiff", "Bill"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableDefine);

        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldTraiff, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMeterCode, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .addComponent(jButtonSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMeterCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTraiff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTraiffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTraiffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTraiffActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        customer x =new customer();
        String meterCode = jTextFieldMeterCode.getText();
        String traiff = jTextFieldTraiff.getText() ;
        if (!meterCode.equals("")&& !traiff.equals("")){
             int meter = Integer.parseInt(meterCode);
             float Traiff = Float.parseFloat(traiff);
             x.tariffGUI(meter,Traiff);
            JOptionPane.showMessageDialog(this, "traiff added  ");
            addRowToTable(meter);
            resetPanelData();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Please Fill All Information");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldMeterCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMeterCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMeterCodeActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        // TODO add your handling code here:
        String meterCode = jTextFieldMeterCode.getText();
        if (meterCode.equals("")){
        JOptionPane.showMessageDialog(this, "Enter please metercode   ");
        }
        else{
        int meter = Integer.parseInt(meterCode);
        addRowToTable(meter);
        }
    }//GEN-LAST:event_jButtonSearchActionPerformed
        private void addRowToTable(int meterCode) {
        String query;
        DefaultTableModel model = (DefaultTableModel) jTableDefine.getModel() ;
        model.setRowCount(0);
        Object data[] = new Object[5];
             query="select * from  customer where meterCode = " + meterCode;
             try {
             r = ss.executeQuery(query) ;
             while (r.next()){
                data[0] = r.getString("userName");
                data[1] = r.getInt("meterCode") ;
                data[2] = r.getString("region") ;
                data[3] = r.getFloat("traiff") ;
                data[4] = r.getInt("bill") ;
                model.addRow(data);
             }
             
            }catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }      
             
        }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableDefine;
    private javax.swing.JTable jTableDefine1;
    private javax.swing.JTextField jTextFieldMeterCode;
    private javax.swing.JTextField jTextFieldTraiff;
    // End of variables declaration//GEN-END:variables
    private void resetPanelData() {
        jTextFieldMeterCode.setText("");
        jTextFieldTraiff.setText("");

    }
    

}

