/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal.java.project.PanelPackege;

import javax.swing.table.DefaultTableModel;
import static pkgfinal.java.project.FinalJavaProject.arr;
import static pkgfinal.java.project.FinalJavaProject.numberOfCustomers;

/**
 *
 * @author win7win7
 */
public class ViewTotalCollected extends javax.swing.JPanel {

    /**
     * Creates new form ViewTotalCollected
     */
    public ViewTotalCollected() {
        initComponents();
        int totalCollected = addRowToTable();
        jTextFieldTotalCollected.setText(totalCollected+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTotalCollected = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldTotalCollected = new javax.swing.JTextField();

        jTableTotalCollected.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "user Name", "Meter Code", "Bill", "Region"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableTotalCollected);

        jLabel1.setText("Total Collected");

        jTextFieldTotalCollected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalCollectedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldTotalCollected, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldTotalCollected, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTotalCollectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalCollectedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalCollectedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTotalCollected;
    private javax.swing.JTextField jTextFieldTotalCollected;
    // End of variables declaration//GEN-END:variables

    private int addRowToTable() {
        DefaultTableModel model = (DefaultTableModel) jTableTotalCollected.getModel();
        model.setRowCount(0);
        int totalCollectet=0 ;
        Object data[] = new Object[4];
        for (int i = 0; i < numberOfCustomers; i++) {
            data[0] = arr.get(i).userName;
            data[1] = arr.get(i).meterCode;
            data[2] = arr.get(i).bill;
            data[3] = arr.get(i).region ;
            model.addRow(data);
            totalCollectet+= arr.get(i).bill ;
        }
        return totalCollectet ;
    }

}
